INSERT INTO users(name, age) VALUES("Valerie", 26);
INSERT INTO users(name, age) VALUES("Robert", 28);
INSERT INTO users(name, age) VALUES("Mary", 22);
INSERT INTO users(name, age) VALUES("Josephine", 40);
INSERT INTO users(name, age) VALUES("Alan", 42);
INSERT INTO users(name, age) VALUES("Ming", 43);
INSERT INTO users(name, age) VALUES("Katya", 50);
INSERT INTO users(name, age) VALUES("Win", 44);
INSERT INTO users(name, age) VALUES("Adam", 44);
INSERT INTO users(name, age) VALUES("Michael", 37);
INSERT INTO users(name, age) VALUES("Gregory", 34);
INSERT INTO users(name, age) VALUES("Henry", 35);
INSERT INTO users(name, age) VALUES("Sean", 26);
INSERT INTO users(name, age) VALUES("Levine", 25);
INSERT INTO users(name, age) VALUES("Cartman", 24);
INSERT INTO users(name, age) VALUES("Butters", 24);
INSERT INTO users(name, age) VALUES("Kevin", 33);
INSERT INTO users(name, age) VALUES("Kailyn", 42);
INSERT INTO users(name, age) VALUES("Happy", 35);
INSERT INTO users(name, age) VALUES("Dr Dre", 36);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Travel Gear", "Merchandise", 30000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Luggage Durable", "Merchandise", 20000.00, "March 5, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Yoga Mat Revolutionary", "Merchandise", 5000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("3D Headphones", "Merchandise", 50000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Healthcare documentary", "Film", 5000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cloth Bags Unique", "Merchandise", 2000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("3D printer", "Merchandise", 25000.00, "January 6, 2018", "January 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Revolutionary programming toy", "Merchandise", 20000.00, "June 2, 2018", "June 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bamboo bacteria resistant bathroom mat", "Merchandise", 5500.00, "June 6, 2018", "June 31, 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Travel Gear", "Merchandise", 30000.00, "January 6, 2018", "January 31, 2018");

INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 1, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (300.50, 2, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100.50, 3, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (150.50, 4, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.00, 5, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 6, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 1, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 2, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 1, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 3, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 4, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 1, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 9, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 9, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 8, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 8, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 7, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 6, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 6, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 6, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 5, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 5, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 3, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200.50, 3, 4);